### ISSUE TITLE
Some issues with building and running mpc4j according to the demonstration you provided.

### ISSUE THREAD

**Issue by qwerfdg** [alibaba-edu/mpc4j#13]
1. Why I haven't got "libmpc4j-native-tool.dylib" and "libmpc4j-native-fhe.dylib" under “mpc4j/mpc4j-native-tool”?I successfully compiled them and saw the following output ”[100%] Built target mc4j-native-tool“ . But I'm not sure if I saw "[100%] Linking CXX shared library libmpc4j-native-tool.dylib".
![image](https://github.com/alibaba-edu/mpc4j/assets/40300988/7bddda47-f48d-4e47-bcb6-a3356bea09fa)
2. After setting "VM Options", I can't apply it.
![image](https://github.com/alibaba-edu/mpc4j/assets/40300988/5b402c23-3a67-4eea-83e4-78834e78330a)
So I clicked "OK" then got nothing here.
![image](https://github.com/alibaba-edu/mpc4j/assets/40300988/0a3b2769-5b1b-4310-9212-967651118ca2)
And no Green Arrows showing on the left.
![image](https://github.com/alibaba-edu/mpc4j/assets/40300988/efe0e0ba-4f1e-414b-9384-17d626764d40)
I tried to run but got problems.
![image](https://github.com/alibaba-edu/mpc4j/assets/40300988/077fe618-9c6c-421e-a397-c9b21033a673)
By the way, my system is ubuntu18.04.

Any help or suggest means a lot to me. Thanks!

**Comment by liuweiran900217** [comment]
For the first problem, I see that you successfully compiled and generated the library with the name "libmpc4j-native-tool.so", which is what you need in Ubuntu (and other Linux systems like CentOS) . "libmpc4j-native-tool.dylib" is the name for MacOS system. You need to compile the C/C++ project in "mpc4j-native-fhe" to generate "libmpc4j-native-fhe.so" (for Linux system) or "libmpc4j-native-fhe.dylib" (for MacOS systems).

For the second problem, I think the reason is that you do not correctly config the JDK for IntelliJ IDEA. Right-click the root project "mpc4j", select "Open module settings...", and select "Project", please check if the SDK is configured as follows (you can config any SDK with a version higher than or equal to 1.8).
![image](https://github.com/alibaba-edu/mpc4j/assets/7699223/f44b070f-d35e-4b40-b3c4-4652baea611d)

Please feel free to let me know if the above procedure can solve your problems.

**Comment by liuweiran900217** [comment]
Thank you very much for providing the detailed information. We found that we missed a file (OpBoostPtoConfig) when we commit v1.0.7. Now we add the file and re-create v1.0.7. Please pull the current version and see if you can successfully compile and run OpBoost.

**Comment by qwerfdg** [comment]
Thanks a lot! I successfully run these tests. 
![image](https://github.com/alibaba-edu/mpc4j/assets/40300988/2aca9889-13d3-4be3-8f28-52f0c6c69435)
By the way, mpc4j is suitable for the following operating system and Java version.
![image](https://github.com/alibaba-edu/mpc4j/assets/40300988/33a83b31-2a22-4bac-947a-3206bd1ab558)
