### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no mpc4j-native-tool in java.library.path

### ISSUE THREAD

**Issue by aaaaaa1** [alibaba-edu/mpc4j#15]
咨询下，mpc4j-native-tool在centos7.6环境编译生成的cmake-build-release文件夹可以在Windows上IntelliJ IDEA进行使用么？参考了https://github.com/alibaba-edu/mpc4j说明中Demonstration部分的第8点进行配置，即在VM进行配置-Djava.library.path=我放路径，结果会报错，如图：
![image](https://github.com/alibaba-edu/mpc4j/assets/5926342/e01802ca-c8c0-47a1-acb8-82689442002f)
编译后路径如图：
![image](https://github.com/alibaba-edu/mpc4j/assets/5926342/b754ea10-64f2-4d49-8817-771ee584853e)
在IntelliJ IDEA上如何才能运行mpc4j-native-tool与mpc4j-native-fhe编译后cmake-build-release

**Comment by liuweiran900217** [comment]
As far as I know, you cannot **directly** use the library compiled by a Linux-like system on Windows. This is the reason why we try to provide pure-Java implementation for other schemes or protocols. However, currently we cannot provide puer-Java alternative for FHE-based solution since there is no pure-Java version for SEAL. We have a plan to do that but it will take time. 

A plausible solution would be to use a cross-compile tool (See https://www.tutorialspoint.com/cross-compile-static-library-from-linux-for-windows for more details) but we haven't tried yet.

**Comment by aaaaaa1** [comment]
好的，谢谢老师，我在linux上开发试试
