### ISSUE TITLE
Begginer question for project compilation and usage inside another project

### ISSUE THREAD

**Issue by damesca** [alibaba-edu/mpc4j#8]
Hi, I'm very interested in using this cool project within another one. I'm very begginer for project compilation tools and I would like to ask for a recommendation on how to achieve what I want.

Basically, I want to embed mpc4j inside another java project, more specifically a multiproject built with gradle. My structure would be:

JavaSrcProject
|----Subproject1
|----Subproject2
      |----mpc4j

My intention is to leave Subproject2 as a wrapper for JavaSrcProject to interact with mpc4j. I am trying to include mpc4j as a dependency for Subproject2, using: 
dependencies { implementation files(/local/path/to/jar) }

However, I am struggling with mpc4j-native dependencies, because I don't know how to include them as well.

Any suggestions or clarifications would be greatly appreciated.
Thanks in advance.

**Comment by liuweiran900217** [comment]
Thank you very much for your interest in mpc4j!

I believe you have successfully obtained the jar file (since you mentioned that you placed the jar file in /local/path/to/jar). 
Including native dependencies in the project would be a little bit tricky. Here I provide some solutions and hope one of them (maybe all of them) can work well.

If you really want to use the native implementation, you need to first directly compile and obtain the .so file based on `mpc4j-native-tool`. The name of the obtained .so file would be libmpc4j-native-tool.so. Then, there are two choices:

1. You can just compile and obtain your own jar and execute it with the same JVM parameter: -Djava.library.path=/local/path/to/so. Note that this is exactly what we do when we execute other modules in mpc4j using mpc4j-common-tool. 

2. The module `mpc4j-common-jnagmp` uses another way of including the native library. In its resource file, you can see that there are some .so related to distinct platforms. This is the way why `mpc4j-common-jnagmp` can be used without installing gmp. You can try to do the following steps to include native libmpc4j-native-tool.so into your project:
    a. compile and obtain libmpc4j-native-tool.so based on `mpc4j-native-tool`.
    b. place libmpc4j-native-tool.so into the resource file of `mpc4j-common-tool`.
    c. compile and obtain the jar file for mpc4j. You can see that libmpc4j-native-tool.so is included in `mpc4j-common-tool.jar`.
    d. Use this jar file in your project.

3. mpc4j provides pure-java implementations for all tools in mpcj4-common-tool. If you do not need very efficient implementation, use the java alternatives directly.

Please feel free to let me know if the above solutions are suitable for you. I will be very happy if you can tell me why you want to use mpc4j (maybe via email).

**Comment by damesca** [comment]
Thanks a lot for your response. I have finally solved my issue using the java implementations for common-tool. However, I will probably come back to the other possibilities in the near future. I'll reach you by email to tell you about how I'm using mpc4j.

Kind regards!
